CREATE OR REPLACE DATABASE Ballgame;

CREATE OR REPLACE TABLE Ballgame.Players (
	ID		VARCHAR(128) primary key, #SteamID 
	FUNDS 	INT
);

CREATE OR REPLACE TABLE Ballgame.Towers (
	ID			INT auto_increment primary key, 
	FK_PLAYER	INT NOT NULL,
	TOWER_TYPE	INT NOT NULL,
	X_POSITION	SMALLINT NOT NULL,
	Y_POSITION	SMALLINT NOT NULL,
	KILLS		INT NOT NULL DEFAULT 0,
	ACTIVE		BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT `fk_player_towers`
		FOREIGN KEY (FK_PLAYER) REFERENCES Ballgame.Players (ID)
		ON DELETE CASCADE
		ON UPDATE RESTRICT
);
	
CREATE OR REPLACE TABLE Ballgame.Research (
	ID				INT auto_increment primary key,
	FK_PLAYER		INT NOT NULL,
	RESEARCH_TYPE	INT NOT NULL,
	CONSTRAINT `fk_player_research`
		FOREIGN KEY (FK_PLAYER) REFERENCES Ballgame.Players (ID)
		ON DELETE CASCADE
		ON UPDATE RESTRICT
);
	
CREATE OR REPLACE TABLE Ballgame.Game_History (
	ID				INT auto_increment primary key,
	FK_PLAYER		INT NOT NULL,
	TOTAL_KILLS		INT NOT NULL,
	TOTAL_EARNED	INT NOT NULL,
	TIME_PLAYED		INT NOT NULL,
	GAME_TIME		TIMESTAMP,
	CONSTRAINT `fk_player_gamehistory`
		FOREIGN KEY (FK_PLAYER) REFERENCES Ballgame.Players (ID)
		ON DELETE CASCADE
		ON UPDATE RESTRICT
);
	
CREATE OR REPLACE TABLE Ballgame.Tower_Transaction (
	ID					INT auto_increment primary key,
	FK_PLAYER			INT NOT NULL,
	FK_TOWER			INT NOT NULL, 
	COST				INT NOT NULL,
	TRANSACTION_DATE	TIMESTAMP,
	CONSTRAINT `fk_player_towerTransaction`
		FOREIGN KEY (FK_PLAYER) REFERENCES Ballgame.Players (ID)
		ON DELETE CASCADE
		ON UPDATE RESTRICT
	CONSTRAINT `fk_tower_transaction`
		FOREIGN KEY (FK_TOWER) REFERENCES Ballgame.Tower (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT
);	
CREATE OR REPLACE TABLE Ballgame.Research_Transaction (
	ID					INT auto_increment primary key,
	FK_PLAYER			INT NOT NULL,
	FK_RESERCH			INT NOT NULL,
	COST				INT NOT NULL,
	TRANSACTION_DATE	TIMESTAMP,
	CONSTRAINT `fk_player_researchTransaction`
		FOREIGN KEY (FK_PLAYER) REFERENCES Ballgame.Players (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT
	CONSTRAINT `fk_reseach_transaction`
		FOREIGN KEY (FK_RESEARCH) REFERENCES Ballgame.Research (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT
);
